
def raise_err(err : str) -> None:
    print(err)
    exit(1)
